apiVersion: skaffold/v2alpha2
kind: Config
build:
  artifacts:
  - image: node-example
    context: node
    sync:
      infer:
      - 'src/**/*.js'
  - image: python-reload
    context: python
    sync:
      infer:
      - 'src/**/*.py'
